plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fastkeyboard.nova'
    compileSdk 35

    defaultConfig {
        applicationId 'com.fastkeyboard.nova'
        minSdk 23
        targetSdk 35
        versionCode 23
        versionName '1.33'
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
