plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fastkeyboard.nova'
    compileSdk 35

    defaultConfig {
        applicationId 'com.fastkeyboard.nova'
        minSdk 23
        targetSdk 35
        versionCode 37
        versionName "1.37"
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
